package com.example.util

object AppStrings {

    fun get(key: String, lang: String): String {
        val map = when (lang) {
            "fr" -> FR
            "en" -> EN
            else -> AR
        }
        return map[key] ?: AR[key] ?: key
    }

    private val AR = mapOf(
        "app_title" to "صلاتي ومواقيت الصلاة",
        "menu_button" to "القائمة",
        "next_prayer" to "الصلاة القادمة",
        "remaining" to "يتبقى",
        "remaining_on_adhan" to "يتبقى %s على أذان %s",
        "iqama" to "الإقامة",
        "fajr" to "الفجر",
        "sunrise" to "الشروق",
        "dhuhr" to "الظهر",
        "asr" to "العصر",
        "maghrib" to "المغرب",
        "isha" to "العشاء",
        "jumuah" to "الجمعة",
        "all_prayers" to "جميع الصلوات",
        
        // Tabs
        "tab_language" to "اللغة",
        "tab_location_calc" to "المكان والحساب",
        "tab_alerts" to "التنبيهات",
        "tab_adhan" to "الأذان",
        "tab_ramadan" to "رمضان",
        "tab_salawat" to "الصلاة على النبي ﷺ",
        "tab_notification_widget" to "شريط الإشعارات والتطبيقات المصغرة",
        
        // Tab 1: Language
        "select_language" to "اختر لغة التطبيق",
        "arabic" to "العربية",
        "english" to "English",
        "french" to "Français",
        
        // Tab 2: Location & Calculation
        "location_header" to "تحديد الموقع",
        "location_manual" to "تحديد الموقع يدويًا",
        "location_auto" to "تحديد الموقع تلقائيًا من الإنترنت",
        "auto_loc_btn" to "جلب الموقع الجغرافي الحالي",
        "loc_detecting" to "جارٍ تحديد الموقع...",
        "loc_success" to "تم تحديد الموقع بنجاح",
        "loc_error" to "تعذر تحديد الموقع تلقائيًا، يمكنك إدخاله يدويًا",
        "city_name" to "اسم المدينة / الدولة",
        "latitude" to "خط العرض (Latitude)",
        "longitude" to "خط الطول (Longitude)",
        "save_location" to "حفظ الموقع",
        "presets_label" to "مدن رئيسية مقترحة",
        
        "timezone_header" to "المنطقة الزمنية",
        "dst_header" to "التوقيت الصيفي",
        "dst_auto" to "تلقائي",
        "dst_on" to "مفعل (+1 ساعة)",
        "dst_off" to "معطل",
        
        "calc_method_header" to "طرق حساب الصلاة",
        "calc_method_desc" to "اختر الهيئة أو الطريقة المعتمدة لحساب المواقيت",
        
        "madhab_header" to "المذهب المعتمد لصلاة العصر",
        "shafii" to "الشافعي",
        "maliki" to "المالكي",
        "hanbali" to "الحنبلي",
        "hanafi" to "الحنفي",
        
        "manual_adj_header" to "تعديل أوقات الصلاة يدويًا",
        "manual_adj_desc" to "تقديم (+) أو تأخير (-) الدقائق لكل صلاة بشكل مستقل",
        "minutes_suffix" to "دقيقة",
        
        "time_format_header" to "تنسيق الوقت",
        "format_12h" to "12 ساعة (ص / م)",
        "format_24h" to "24 ساعة",
        
        "hijri_calendar_header" to "التقويم الهجري",
        "hijri_adjustment" to "تعديل التاريخ الهجري (تقديم أو تأخير)",
        "days_suffix" to "يوم",
        
        // Tab 3: Alerts
        "alerts_title" to "التنبيهات المخصصة",
        "add_alert_btn" to "إضافة تنبيه جديد",
        "unlimited_alerts_note" to "يمكنك إضافة عدد لا نهائي من التنبيهات وتخصيصها بشكل مستقل",
        "target_prayer" to "الصلاة المستهدفة",
        "time_before_adhan" to "وقت التنبيه قبل الأذان",
        "custom_minutes" to "مدة مخصصة (دقائق)",
        "repeat_days" to "أيام تكرار التنبيه",
        "all_days" to "جميع الأيام",
        "alert_ringtone" to "نغمة التنبيه",
        "pick_audio_file" to "اختيار ملف صوتي من الهاتف",
        "test_alert" to "تجربة التنبيه الآن",
        "save_alert" to "حفظ التنبيه",
        "delete_alert" to "حذف التنبيه",
        "no_alerts" to "لا توجد تنبيهات مضافة بعد. اضغط لإضافة تنبيه جديد.",
        
        // Permissions Section
        "permissions_header" to "الأشياء والأذونات المطلوبة لدقة التنبيهات والأذان",
        "perm_battery_title" to "1. استثناء قيود البطارية",
        "perm_battery_desc" to "ضروري لمنع النظام من إيقاف الأذان والتنبيهات في الخلفية عند قفل الهاتف.",
        "perm_battery_action" to "طلب استثناء البطارية",
        "perm_overlay_title" to "2. الظهور فوق التطبيقات الأخرى",
        "perm_overlay_desc" to "مطلوب لإظهار شاشة الأذان الكبيرة والتنبيهات عند انطلاق الأذان.",
        "perm_overlay_action" to "منح إذن الظهور فوق التطبيقات",
        "perm_autostart_title" to "3. التشغيل التلقائي بعد إعادة التشغيل",
        "perm_autostart_desc" to "يتم إعادة جدولة جميع الأذانات والتنبيهات تلقائيًا عند تشغيل الجهاز.",
        "perm_files_title" to "4. الوصول لملفات الوسائط بالجهاز",
        "perm_files_desc" to "لاختيار أصوات الأذان، التنبيهات، ملفات ZIP، ومقاطع الفيديو من هاتفك.",
        "perm_files_action" to "منح إذن الوصول للملفات",
        "status_granted" to "مفعّل وممنوح ✓",
        "status_needed" to "يحتاج إلى تفعيل",
        
        // Tab 4: Adhan
        "adhan_audio_section" to "صوت الأذان",
        "adhan_audio_desc" to "اختر ملف صوتي مخصص لكل صلاة على حدة من الهاتف أو الأصوات المدمجة",
        "time_alert_section" to "التنبيه بالوقت",
        "time_alert_desc" to "عند حلول الوقت ينطلق التنبيه بالوقت أولاً، ومباشرة بعده الأذان دون تأخير",
        "dua_section" to "دعاء بعد الأذان",
        "dua_desc" to "اختر مقطع فيديو لدعاء ما بعد الأذان لكل صلاة من الهاتف",
        "adhan_screen_section" to "شاشة الأذان",
        "adhan_screen_desc" to "شاشة مخصصة لكل صلاة، تظهر على شاشة القفل وتدعم صور من ملف ZIP",
        "zip_images_picker" to "اختيار ملف صور ZIP من الهاتف",
        "zip_images_loaded" to "تم استخراج %d صورة من الملف",
        "display_mode" to "إعداد عرض الصور",
        "mode_slideshow" to "عرض متتابع (شرائح)",
        "mode_static" to "صورة ثابتة",
        "slide_duration" to "مدة عرض كل صورة",
        "preview_screen" to "معاينة شاشة الأذان",
        "preview_audio" to "تشغيل ومعاينة",
        "stop_audio" to "إيقاف",
        "adhan_label_prefix" to "أذان",
        
        // Tab 5: Ramadan
        "ramadan_cannon_title" to "مدفع الإفطار",
        "ramadan_cannon_desc" to "تشغيل فيديو مدفع الإفطار المختار من هاتفك قبل أذان المغرب مباشرة في رمضان",
        "pick_cannon_video" to "اختيار فيديو مدفع الإفطار من الهاتف",
        "preview_cannon_video" to "معاينة فيديو المدفع",
        "mesaharaty_title" to "المسحراتي",
        "mesaharaty_desc" to "فيديو المسحراتي للتنبيه لوجبة السحور في رمضان",
        "pick_mesaharaty_video" to "اختيار فيديو المسحراتي من الهاتف",
        "preview_mesaharaty_video" to "معاينة فيديو المسحراتي",
        "mesaharaty_timing" to "موعد تنبيه المسحراتي",
        "timing_fixed" to "ساعة ثابتة (مثل 02:30 صباحًا)",
        "timing_before_fajr" to "قبل الفجر بمدة مخصصة",
        "before_fajr_val" to "قبل الفجر بـ (دقائق)",
        
        // Tab 6: Salawat
        "salawat_title" to "الصلاة على النبي ﷺ",
        "salawat_desc" to "نظام تذكير صوتي متكامل بالصلاة والسلام على رسول الله ﷺ يعمل طوال 24 ساعة",
        "salawat_zip_picker" to "اختيار ملف أصوات تذكير ZIP من الهاتف",
        "salawat_zip_loaded" to "تم استخراج %d صوت تذكير",
        "salawat_interval" to "فترة التذكير (تتكرر طوال اليوم)",
        "salawat_mode" to "طريقة اختيار صوت التذكير",
        "mode_order" to "بالترتيب (1 ثم 2 ثم 3... ثم العودة)",
        "mode_random" to "عشوائي",
        "mode_specific" to "صوت محدد",
        "countdown_label" to "التذكير القادم بعد",
        "test_salawat_now" to "تشغيل التذكير الآن",
        "salawat_active" to "التذكيرات مفعلة طوال اليوم",
        "salawat_disabled" to "التذكيرات متوقفة",
        
        // General
        "save_success" to "تم الحفظ بنجاح",
        "close" to "إغلاق",
        "cancel" to "إلغاء",
        "ok" to "موافق",
        "today" to "اليوم"
    )

    private val EN = mapOf(
        "app_title" to "My Prayer & Adhan Times",
        "menu_button" to "Menu",
        "next_prayer" to "Next Prayer",
        "remaining" to "Remaining",
        "remaining_on_adhan" to "%s remaining until %s Adhan",
        "iqama" to "Iqama",
        "fajr" to "Fajr",
        "sunrise" to "Sunrise",
        "dhuhr" to "Dhuhr",
        "asr" to "Asr",
        "maghrib" to "Maghrib",
        "isha" to "Isha",
        "jumuah" to "Jumu'ah",
        "all_prayers" to "All Prayers",
        
        // Tabs
        "tab_language" to "Language",
        "tab_location_calc" to "Location & Calc",
        "tab_alerts" to "Alerts",
        "tab_adhan" to "Adhan",
        "tab_ramadan" to "Ramadan",
        "tab_salawat" to "Salawat on the Prophet ﷺ",
        "tab_notification_widget" to "Notification Bar & Widgets",
        
        // Tab 1: Language
        "select_language" to "Select App Language",
        "arabic" to "العربية",
        "english" to "English",
        "french" to "Français",
        
        // Tab 2: Location & Calculation
        "location_header" to "Location Settings",
        "location_manual" to "Manual Location Selection",
        "location_auto" to "Automatic Location from Internet/GPS",
        "auto_loc_btn" to "Fetch Current GPS Location",
        "loc_detecting" to "Detecting location...",
        "loc_success" to "Location updated successfully",
        "loc_error" to "Unable to detect location, please enter manually",
        "city_name" to "City / Country Name",
        "latitude" to "Latitude",
        "longitude" to "Longitude",
        "save_location" to "Save Location",
        "presets_label" to "Major Suggested Cities",
        
        "timezone_header" to "Timezone",
        "dst_header" to "Daylight Saving Time (DST)",
        "dst_auto" to "Auto",
        "dst_on" to "Enabled (+1 Hour)",
        "dst_off" to "Disabled",
        
        "calc_method_header" to "Prayer Calculation Methods",
        "calc_method_desc" to "Select the recognized calculation convention worldwide",
        
        "madhab_header" to "Asr Juristic Method (Madhab)",
        "shafii" to "Shafi'i",
        "maliki" to "Maliki",
        "hanbali" to "Hanbali",
        "hanafi" to "Hanafi",
        
        "manual_adj_header" to "Manual Prayer Time Adjustments",
        "manual_adj_desc" to "Add (+) or subtract (-) minutes for each prayer independently",
        "minutes_suffix" to "minutes",
        
        "time_format_header" to "Time Format",
        "format_12h" to "12 Hours (AM / PM)",
        "format_24h" to "24 Hours",
        
        "hijri_calendar_header" to "Hijri Calendar",
        "hijri_adjustment" to "Adjust Hijri Date (+/- Days)",
        "days_suffix" to "days",
        
        // Tab 3: Alerts
        "alerts_title" to "Custom Alerts",
        "add_alert_btn" to "Add New Alert",
        "unlimited_alerts_note" to "You can add unlimited alerts and customize each independently",
        "target_prayer" to "Target Prayer",
        "time_before_adhan" to "Alert Time Before Adhan",
        "custom_minutes" to "Custom Duration (Minutes)",
        "repeat_days" to "Repetition Days",
        "all_days" to "Every Day",
        "alert_ringtone" to "Alert Ringtone",
        "pick_audio_file" to "Choose Audio File from Phone",
        "test_alert" to "Test Alert Now",
        "save_alert" to "Save Alert",
        "delete_alert" to "Delete Alert",
        "no_alerts" to "No alerts added yet. Tap to add a new alert.",
        
        // Permissions Section
        "permissions_header" to "Required Permissions for Accurate Alarms & Adhan",
        "perm_battery_title" to "1. Battery Optimization Exemption",
        "perm_battery_desc" to "Crucial to prevent the OS from killing Adhan & alerts while the phone is locked.",
        "perm_battery_action" to "Request Battery Exemption",
        "perm_overlay_title" to "2. Draw Over Other Apps",
        "perm_overlay_desc" to "Needed to display the full Adhan screen on top of apps and lock screen.",
        "perm_overlay_action" to "Grant Overlay Permission",
        "perm_autostart_title" to "3. Auto-start After Reboot",
        "perm_autostart_desc" to "Automatically reschedules all Adhans and alerts when the device boots.",
        "perm_files_title" to "4. Device Storage & Media Access",
        "perm_files_desc" to "Allows selecting audio, videos, ZIP files, and photos from your device.",
        "perm_files_action" to "Grant Media Access",
        "status_granted" to "Granted ✓",
        "status_needed" to "Action Needed",
        
        // Tab 4: Adhan
        "adhan_audio_section" to "Adhan Audio",
        "adhan_audio_desc" to "Select custom audio file for each prayer independently or use built-in recordings",
        "time_alert_section" to "Time Announcement / Pre-Chime",
        "time_alert_desc" to "At adhan time, the time chime sounds first, immediately followed by the Adhan",
        "dua_section" to "Du'a After Adhan",
        "dua_desc" to "Select a post-adhan supplication video from your phone for each prayer",
        "adhan_screen_section" to "Adhan Screen",
        "adhan_screen_desc" to "Custom lock-screen view per prayer, supports images from a ZIP file",
        "zip_images_picker" to "Choose Image ZIP File from Phone",
        "zip_images_loaded" to "%d images extracted from ZIP",
        "display_mode" to "Image Display Mode",
        "mode_slideshow" to "Slideshow (Sequential)",
        "mode_static" to "Static Image",
        "slide_duration" to "Duration per Image",
        "preview_screen" to "Preview Adhan Screen",
        "preview_audio" to "Play Preview",
        "stop_audio" to "Stop",
        "adhan_label_prefix" to "Adhan",
        
        // Tab 5: Ramadan
        "ramadan_cannon_title" to "Iftar Cannon",
        "ramadan_cannon_desc" to "Plays chosen Iftar cannon video right before Maghrib adhan in Ramadan",
        "pick_cannon_video" to "Select Iftar Cannon Video from Phone",
        "preview_cannon_video" to "Preview Cannon Video",
        "mesaharaty_title" to "Mesaharaty",
        "mesaharaty_desc" to "Mesaharaty video for Suhoor wake-up in Ramadan",
        "pick_mesaharaty_video" to "Select Mesaharaty Video from Phone",
        "preview_mesaharaty_video" to "Preview Mesaharaty Video",
        "mesaharaty_timing" to "Mesaharaty Alert Timing",
        "timing_fixed" to "Fixed Time (e.g. 02:30 AM)",
        "timing_before_fajr" to "Before Fajr by Custom Duration",
        "before_fajr_val" to "Before Fajr by (Minutes)",
        
        // Tab 6: Salawat
        "salawat_title" to "Salawat on the Prophet ﷺ",
        "salawat_desc" to "24/7 audio reminder system sending blessings upon Prophet Muhammad ﷺ",
        "salawat_zip_picker" to "Choose Audio ZIP File from Phone",
        "salawat_zip_loaded" to "%d audio files extracted from ZIP",
        "salawat_interval" to "Reminder Interval (All Day)",
        "salawat_mode" to "Audio Selection Mode",
        "mode_order" to "In Order (1, 2, 3... repeat)",
        "mode_random" to "Random",
        "mode_specific" to "Specific Audio",
        "countdown_label" to "Next Reminder In",
        "test_salawat_now" to "Play Reminder Now",
        "salawat_active" to "Reminders Active All Day",
        "salawat_disabled" to "Reminders Disabled",
        
        // General
        "save_success" to "Saved successfully",
        "close" to "Close",
        "cancel" to "Cancel",
        "ok" to "OK",
        "today" to "Today"
    )

    private val FR = mapOf(
        "app_title" to "Mes Prières et Heures d'Adhan",
        "menu_button" to "Menu",
        "next_prayer" to "Prochaine Prière",
        "remaining" to "Restant",
        "remaining_on_adhan" to "Il reste %s avant l'Adhan du %s",
        "iqama" to "Iqama",
        "fajr" to "Fadjr",
        "sunrise" to "Lever du soleil",
        "dhuhr" to "Dhohr",
        "asr" to "Asr",
        "maghrib" to "Maghrib",
        "isha" to "Icha",
        "jumuah" to "Djoumou'a",
        "all_prayers" to "Toutes les prières",
        
        // Tabs
        "tab_language" to "Langue",
        "tab_location_calc" to "Lieu et Calcul",
        "tab_alerts" to "Rappels",
        "tab_adhan" to "Adhan",
        "tab_ramadan" to "Ramadan",
        "tab_salawat" to "Prières sur le Prophète ﷺ",
        "tab_notification_widget" to "Barre de notifications et widgets",
        
        // Tab 1: Language
        "select_language" to "Choisir la langue de l'application",
        "arabic" to "العربية",
        "english" to "English",
        "french" to "Français",
        
        // Tab 2: Location & Calculation
        "location_header" to "Paramètres de localisation",
        "location_manual" to "Sélection manuelle du lieu",
        "location_auto" to "Localisation automatique via Internet/GPS",
        "auto_loc_btn" to "Obtenir la position GPS actuelle",
        "loc_detecting" to "Recherche de la position...",
        "loc_success" to "Position mise à jour avec succès",
        "loc_error" to "Impossible de localiser, veuillez saisir manuellement",
        "city_name" to "Nom de la ville / Pays",
        "latitude" to "Latitude",
        "longitude" to "Longitude",
        "save_location" to "Enregistrer la position",
        "presets_label" to "Villes principales suggérées",
        
        "timezone_header" to "Fuseau horaire",
        "dst_header" to "Heure d'été (DST)",
        "dst_auto" to "Automatique",
        "dst_on" to "Activé (+1 heure)",
        "dst_off" to "Désactivé",
        
        "calc_method_header" to "Méthodes de calcul de la prière",
        "calc_method_desc" to "Choisissez la convention de calcul mondialement reconnue",
        
        "madhab_header" to "Méthode juridique pour Asr (Madhab)",
        "shafii" to "Chaféite",
        "maliki" to "Malikite",
        "hanbali" to "Hanbalite",
        "hanafi" to "Hanafite",
        
        "manual_adj_header" to "Ajustement manuel des horaires",
        "manual_adj_desc" to "Ajoutez (+) ou retranchez (-) des minutes pour chaque prière",
        "minutes_suffix" to "minutes",
        
        "time_format_header" to "Format de l'heure",
        "format_12h" to "12 Heures (AM / PM)",
        "format_24h" to "24 Heures",
        
        "hijri_calendar_header" to "Calendrier Hégirien",
        "hijri_adjustment" to "Ajuster la date hégirienne (+/- Jours)",
        "days_suffix" to "jours",
        
        // Tab 3: Alerts
        "alerts_title" to "Rappels Personnalisés",
        "add_alert_btn" to "Ajouter un rappel",
        "unlimited_alerts_note" to "Vous pouvez ajouter une infinité de rappels et les personnaliser",
        "target_prayer" to "Prière ciblée",
        "time_before_adhan" to "Délai avant l'Adhan",
        "custom_minutes" to "Durée personnalisée (minutes)",
        "repeat_days" to "Jours de répétition",
        "all_days" to "Tous les jours",
        "alert_ringtone" to "Sonnerie de rappel",
        "pick_audio_file" to "Choisir un fichier audio du téléphone",
        "test_alert" to "Tester le rappel maintenant",
        "save_alert" to "Enregistrer le rappel",
        "delete_alert" to "Supprimer le rappel",
        "no_alerts" to "Aucun rappel ajouté pour le moment.",
        
        // Permissions Section
        "permissions_header" to "Autorisations requises pour la précision des alertes",
        "perm_battery_title" to "1. Exemption d'optimisation de batterie",
        "perm_battery_desc" to "Indispensable pour éviter la mise en veille des rappels en arrière-plan.",
        "perm_battery_action" to "Demander l'exemption de batterie",
        "perm_overlay_title" to "2. Affichage par-dessus les applications",
        "perm_overlay_desc" to "Requis pour afficher l'écran d'Adhan complet même sur écran verrouillé.",
        "perm_overlay_action" to "Accorder l'autorisation de superposition",
        "perm_autostart_title" to "3. Démarrage automatique au redémarrage",
        "perm_autostart_desc" to "Reprogramme automatiquement tous les adhans et rappels au redémarrage.",
        "perm_files_title" to "4. Accès aux fichiers et médias",
        "perm_files_desc" to "Permet de charger vos fichiers audio, vidéos, photos et archives ZIP.",
        "perm_files_action" to "Accorder l'accès aux fichiers",
        "status_granted" to "Accordé ✓",
        "status_needed" to "Action requise",
        
        // Tab 4: Adhan
        "adhan_audio_section" to "Audio de l'Adhan",
        "adhan_audio_desc" to "Sélectionnez un fichier audio pour chaque prière ou utilisez les enregistrements intégrés",
        "time_alert_section" to "Annonce de l'heure / Carillon",
        "time_alert_desc" to "À l'heure de la prière, le carillon sonne d'abord, suivi directement par l'Adhan",
        "dua_section" to "Invocation après l'Adhan",
        "dua_desc" to "Choisissez une vidéo d'invocation après l'Adhan pour chaque prière",
        "adhan_screen_section" to "Écran de l'Adhan",
        "adhan_screen_desc" to "Écran dédié par prière, affichable sur écran verrouillé, supporte les images ZIP",
        "zip_images_picker" to "Choisir un fichier ZIP d'images depuis le téléphone",
        "zip_images_loaded" to "%d images extraites du ZIP",
        "display_mode" to "Mode d'affichage des images",
        "mode_slideshow" to "Diaporama (successif)",
        "mode_static" to "Image fixe",
        "slide_duration" to "Durée par image",
        "preview_screen" to "Aperçu de l'écran d'Adhan",
        "preview_audio" to "Écouter l'aperçu",
        "stop_audio" to "Arrêter",
        "adhan_label_prefix" to "Adhan",
        
        // Tab 5: Ramadan
        "ramadan_cannon_title" to "Canon de l'Iftar",
        "ramadan_cannon_desc" to "Joue la vidéo du canon de l'Iftar juste avant l'Adhan du Maghrib pendant le Ramadan",
        "pick_cannon_video" to "Choisir la vidéo du canon depuis le téléphone",
        "preview_cannon_video" to "Aperçu de la vidéo du canon",
        "mesaharaty_title" to "Le Mesaharaty",
        "mesaharaty_desc" to "Vidéo du Mesaharaty pour le réveil du Suhoor pendant le Ramadan",
        "pick_mesaharaty_video" to "Choisir la vidéo du Mesaharaty depuis le téléphone",
        "preview_mesaharaty_video" to "Aperçu de la vidéo du Mesaharaty",
        "mesaharaty_timing" to "Horaire du rappel du Mesaharaty",
        "timing_fixed" to "Heure fixe (ex: 02h30)",
        "timing_before_fajr" to "Avant le Fadjr d'une durée personnalisée",
        "before_fajr_val" to "Avant le Fadjr de (Minutes)",
        
        // Tab 6: Salawat
        "salawat_title" to "Prières sur le Prophète ﷺ",
        "salawat_desc" to "Système de rappel audio 24h/24 pour prier sur le Messager d'Allah ﷺ",
        "salawat_zip_picker" to "Choisir un fichier audio ZIP depuis le téléphone",
        "salawat_zip_loaded" to "%d fichiers audio extraits du ZIP",
        "salawat_interval" to "Intervalle de rappel (Toute la journée)",
        "salawat_mode" to "Mode de sélection audio",
        "mode_order" to "Dans l'ordre (1, 2, 3... recommencer)",
        "mode_random" to "Aléatoire",
        "mode_specific" to "Audio spécifique",
        "countdown_label" to "Prochain rappel dans",
        "test_salawat_now" to "Lancer le rappel maintenant",
        "salawat_active" to "Rappels actifs toute la journée",
        "salawat_disabled" to "Rappels désactivés",
        
        // General
        "save_success" to "Enregistré avec succès",
        "close" to "Fermer",
        "cancel" to "Annuler",
        "ok" to "OK",
        "today" to "Aujourd'hui"
    )
}
